In [12]:
import pandas as pd

lotusdb = pd.read_csv("lotusdb/LOTUS_DB.smi", header=None, sep ="\t")

lotusdb.columns = ["SMILES", "lotus_id"]

lotusdb.shape

(276518, 2)

In [13]:
lotusdb.to_csv("lotusdb/lotusdb.csv", index=False)

In [5]:
coconut = pd.read_csv("coconut/coconut_complete-10-2024.csv")
coconut

/tmp/ipykernel_3472256/2023391647.py:1: DtypeWarning: Columns (38,40,42) have mixed types. Specify dtype option on import or set low_memory=False.
  coconut = pd.read_csv("coconut_complete-10-2024.csv")

,identifier,canonical_smiles,standard_inchi,standard_inchi_key,name,iupac_name,total_atom_count,heavy_atom_count,molecular_weight,exact_molecular_weight,...,direct_parent_classification,np_classifier_pathway,np_classifier_superclass,np_classifier_class,np_classifier_is_glycoside,organisms,collections,dois,synonyms,cas
0,CNP0282693.1,COC1=CC=CC2=C1C(=O)C1=C(O)C3=C(C[C@@](O)(C(=O)...,InChI=1S/C27H29NO10/c1-11-6-12(28)7-18(37-11)3...,ITSGNOIFAJAQHJ-BMFNZSJVSA-N,Esorubicin,"(7~{S},9~{S})-7-[(2~{S},4~{R},6~{S})-4-amino-6...",67,38,527.53,527.17915,...,Tetracenequinones,Polyketides,Polycyclic aromatic polyketides,Anthracyclines,t,NaN,ChEMBL NPs,NaN,4'-Deoxydoxorubicin|63521-85-7|Esorubicin INN|...,63521-85-7
1,CNP0214016.1,COC1=CC2=CC(=C1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](...,InChI=1S/C34H46ClN3O10/c1-18-11-10-12-26(45-9)...,WKPWGQKGSOKKOO-RSFHAFMBSA-N,MAYTANSINE,"[(1~{S},2~{R},3~{S},5~{S},6~{S},16~{E},18~{E},...",94,48,692.21,691.28717,...,Alpha amino acid esters,Polyketides,Macrolides,Ansa macrolides,f,Maytenus buchananii|Maytenus confertiflorus|Ma...,ChEBI NPs|ChEMBL NPs|KNApSaCK|NCI DTP data|Sup...,NaN,Maitansine|Maytansine USAN|Maitansinum|NSC-153...,35846-53-8
2,CNP0185052.1,NC1=NC(N)=C2N=C(CNC3=CC=C(C(=O)N[C@@H](CCCNC(=...,InChI=1S/C27H27N9O6/c28-21-20-22(36-27(29)35-2...,NYQPLPNEESYGNO-IBGZPJMESA-N,Talotrexin,"2-[[(4~{S})-4-carboxy-4-[[4-[(2,4-diaminopteri...",69,42,573.57,573.20843,...,Hippuric acids and derivatives,Alkaloids,NaN,NaN,f,NaN,ChEMBL NPs,NaN,113857-87-7|PT523|Talotrexin INN|A8E516A20K|N(...,113857-87-7
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(COC...,InChI=1S/C16H16N4O8S.Na/c1-26-19-9(8-3-2-4-27-...,URDOHUPGIOGTKV-JTBFTWTJSA-M,CEFUROXIME SODIUM,"sodium (6~{R},7~{R})-3-(carbamoyloxymethyl)-7-...",45,30,446.37,446.05083,...,Cephalosporin 3'-carbamates,Amino acids and Peptides,β-lactams,Cephalosporins,f,NaN,ChEMBL NPs,NaN,Sodium cefuroxime|Anaptivan|Biociclin|Cefuroxi...,56238-63-2
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[N...,InChI=1S/C23H24N6O5S2/c1-34-27-16(14-11-36-23(...,YWKJNRNSJKEFMK-PQFQYKRASA-N,Cefquinome,"(6~{R},7~{R})-7-[[(2~{Z})-2-(2-aminothiazol-4-...",60,36,528.62,528.12496,...,Cephalosporins,Amino acids and Peptides,β-lactams,Cephalosporins,f,NaN,ChEMBL NPs,NaN,84957-30-2|Cobactan|Cefquinoma|HR111V|Z74S078C...,84957-30-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695128,CNP0268134.1,NCCCC1=CC=CC2=C1C(=O)O[C@@]21[C@H]2C[C@H](C3CC...,InChI=1S/C76H97N3O5/c77-35-12-19-47-18-9-22-58...,VPHVGKXEMKGKIP-UIJKDPTQSA-N,NaN,NaN,181,84,1132.63,1131.74282,...,NaN,Alkaloids,NaN,NaN,f,NaN,TCMDB@Taiwan (Traditional Chinese Medicine dat...,NaN,NaN,NaN
695129,CNP0088477.1,CC1(C)O[C@H]2CC(=O)OC[C@@]23[C@@H]1C(=O)[C@@H]...,InChI=1S/C56H68N2O11/c1-51(2)47-46(62)48(63)54...,RBWVJZOOBMGPRJ-XZLTWHOLSA-N,"(1~{S},2~{R},4~{S},7~{R},10~{S},18~{R},21~{S},...","(1~{S},2~{R},4~{S},7~{R},10~{S},18~{R},21~{S},...",137,69,945.16,944.48231,...,Terpene lactones,Terpenoids,NaN,NaN,f,NaN,TCMDB@Taiwan (Traditional Chinese Medicine dat...,NaN,NaN,NaN
695130,CNP0569976.1,C=C1CC[C@@H](C(=O)O)C2[C@H](O)[C@H]3CCC[C@@]24...,InChI=1S/C75H86N2O4S2/c1-45-24-26-57(69(80)81)...,HVZVVHMXQOCCGH-CJWGQLQNSA-N,"(16~{R},19~{S},23~{S},24~{S},27~{S},30~{S},46~...","(16~{R},19~{S},23~{S},24~{S},27~{S},30~{S},46~...",169,83,1143.66,1142.60290,...,NaN,NaN,NaN,NaN,f,NaN,TCMDB@Taiwan (Traditional Chinese Medicine dat...,NaN,NaN,NaN
695131,CNP0090070.1,COCC[C@H]1CC[C@H]2N[C@]13CC[C@@H](CC#C[C@@H]1C...,InChI=1S/C69H96N2O13S2/c1-38(2)39(3)56-58(84-5...,SWHQTPGCJOGMAD-DFGHIQLMSA-N,"(1~{S},2'~{S},4~{S},6'~{R},8~{R},10~{S},10'~{S...","(1~{S},2'~{S},4~{S},6'~{R},8~{R},10~{S},10'~{S...",182,86,1225.66,1224.63538,...,Sesquiterpenoids,Alkaloids,Pseudoalkaloids,Kaurane and Phyllocladane diterpenoids,f,NaN,TCMDB@Taiwan (Traditional Chinese Medicine dat...,NaN,NaN,NaN
695132,CNP0547637.1,C/C=C(\CCO)C(=O)O[C@]1(C)[C@@H](CO)C=C2CSS[C@H...,InChI=1S/C50H58N4O10S2/c1-4-26(9-13-55)46(60)6...,MHYLTRKXBGBFNW-NHGGQQBKSA-N,"[(1~{R},2~{S},12~{R},13~{R},14~{R},15~{R},21~{...","[(1~{R},2~{S},12~{R},13~{R},14~{R},15~{R},21~{...",124,66,939.17,938.35944,...,Psoralens,Polyketides,NaN,NaN,f,NaN,TCMDB@Taiwan (Traditional Chinese Medicine dat...,NaN,NaN,NaN

In [7]:
coconut_reduced = coconut.loc[:, ["identifier", "canonical_smiles"]]

In [10]:
coconut_reduced.to_csv("coconut/coconut_reduced.csv", index=False)

In [1]:
import pandas as pd

coconut = pd.read_csv("coconut/coconut_standardized.csv")

In [6]:
from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(coconut.smiles), total=coconut.shape[0]):
    mol = MolFromSmiles(smiles)
    if mol is not None:
        inchikey = MolToInchiKey(mol)
        inchikeys.append(inchikey)
        inchikeys_wo_last.append(inchikey[:-1])
    else:
        to_drop.append(i)

 33%|███▎      | 227768/695133 [04:11<08:20, 933.10it/s] [13:04:58] WARNING: not removing hydrogen atom without neighbors
 33%|███▎      | 230498/695133 [04:14<11:04, 698.98it/s] [13:05:02] Can't kekulize mol.  Unkekulized atoms: 1 2 5 9 11
 55%|█████▌    | 385536/695133 [07:40<08:12, 628.86it/s] [13:08:27] WARNING: not removing hydrogen atom without neighbors
[13:08:27] WARNING: not removing hydrogen atom without neighbors
 62%|██████▏   | 433161/695133 [08:48<05:24, 806.41it/s] [13:09:36] WARNING: not removing hydrogen atom without neighbors
100%|██████████| 695133/695133 [14:02<00:00, 825.49it/s]

In [10]:
coconut_ = coconut.drop(to_drop)
coconut_["inchikey"] = inchikeys
coconut_["inchikey_wo_last"] = inchikeys_wo_last

In [12]:
coconut_.to_csv("coconut/coconut_w_inchikey.csv", index=False)

In [14]:
from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

lotusdb = pd.read_csv("lotusdb/lotusdb_standardized.csv")
inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(lotusdb.smiles), total=lotusdb.shape[0]):
    mol = MolFromSmiles(smiles)
    if mol is not None:
        inchikey = MolToInchiKey(mol)
        inchikeys.append(inchikey)
        inchikeys_wo_last.append(inchikey[:-1])
    else:
        to_drop.append(i)

100%|██████████| 276518/276518 [05:44<00:00, 803.31it/s]

In [19]:
lotusdb_ = lotusdb.drop(to_drop)
lotusdb_["inchikey"] = inchikeys
lotusdb_["inchikey_wo_last"] = inchikeys_wo_last
lotusdb_.to_csv("lotusdb/lotusdb_w_inchikey.csv", index=False)

# Integration of the two databases

In [28]:
import pandas as pd


lotusdb = pd.read_csv("lotusdb/lotusdb_w_inchikey.csv")
coconut = pd.read_csv("coconut/coconut_w_inchikey.csv")

In [30]:
merged = pd.merge(coconut, lotusdb, on="inchikey_wo_last")
merged_lotusdb = merged.loc[:, "ids_y"].values

In [31]:
lotusdb_not_merged = lotusdb[~lotusdb.loc[:, "ids"].isin(merged_lotusdb)]

In [32]:
final_dataset = pd.concat((coconut, lotusdb_not_merged))
final_dataset = final_dataset.loc[:, ["ids", "smiles", "inchikey_wo_last"]]
final_dataset.to_csv("integrated_dataset_lm_training.csv", index=False)

# Drop duplicates

In [33]:
import pandas as pd

final_dataset = pd.read_csv("integrated_dataset_lm_training.csv")
final_dataset

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
813047,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
813048,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
813049,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
813050,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
813051,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

In [34]:
final_dataset.drop_duplicates("smiles").to_csv("integrated_dataset_lm_training.csv", index=False)

In [35]:
import pandas as pd

final_dataset = pd.read_csv("integrated_dataset_lm_training.csv")
final_dataset

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
810463,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
810464,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
810465,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
810466,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
810467,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

# Take out the smiles from the fine-tuning datasets

## PlantCyc

In [ ]:
import pandas as pd

plantcyc = pd.read_csv("../plantcyc/plantcyc_pathways.csv")

from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(plantcyc.SMILES), total=plantcyc.shape[0]):
    mol = MolFromSmiles(smiles)
    if mol is not None:
        inchikey = MolToInchiKey(mol)
        inchikeys.append(inchikey)
        inchikeys_wo_last.append(inchikey[:-1])
    else:
        to_drop.append(i)

  0%|          | 0/3211 [00:00<?, ?it/s]

  6%|▋         | 204/3211 [00:00<00:01, 2039.41it/s][10:38:06] WARNING: not removing hydrogen atom without neighbors
 13%|█▎        | 408/3211 [00:00<00:01, 1887.42it/s][10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 12.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]'
[10:38:06] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]'
[10:38:06] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@H]1([C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@@H](O)1))OC(=O)[R2]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@H]1([C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@H]1([C@H](O)[C@@H](O)[C@H](O)[C@@H](O)[C@@H](O)1))OC(=O)[R2]'
[10:38:06] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP([O-])(=O)[O-])[C@H](O)[C@@H](O)1))OC(=O)[R2]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP([O-])(=O)[O-])[C@H](O)[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP([O-])(=O)[O-])[C@H](O)[C@@H](O)1))OC(=O)[R2]'
 19%|█▊        | 598/3211 [00:00<00:01, 1877.92it/s][10:38:06] SMILES Parse Error: syntax error while parsing: CC(C)=CCNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'CC(C)=CCNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a' for input: 'CC(C)=CCNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a'
[10:38:06] SMILES Parse Error: syntax error while parsing: CC(\CO)=C\CNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'CC(\CO)=C\CNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a' for input: 'CC(\CO)=C\CNC3(/N=C\N=C1(C(/N=C\N1[C@@H]2(O[C@H](COP(=O)([O-])O[a'
 25%|██▍       | 792/3211 [00:00<00:01, 1900.33it/s][10:38:06] Conflicting single bond directions around double bond at index 12.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 12.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
 37%|███▋      | 1174/3211 [00:00<00:01, 1872.17it/s][10:38:06] SMILES Parse Error: syntax error while parsing: C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]' for input: 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]'
[10:38:06] SMILES Parse Error: syntax error while parsing: C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]' for input: 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]'
[10:38:06] SMILES Parse Error: syntax error while parsing: C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)' for input: 'C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)'
[10:38:06] SMILES Parse Error: syntax error while parsing: C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC2(\C(C1(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=1))=[O+]C3(\C(/C=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))O4)
[10:38:06] SMILES Parse Error: Failed parsing SMILES 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC2(\C(C1(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=1))=[O+]C3(\C(/C=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))O4)' for input: 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC2(\C(C1(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=1))=[O+]C3(\C(/C=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))O4)'
 43%|████▎     | 1396/3211 [00:00<00:00, 1982.05it/s][10:38:06] Conflicting single bond directions around double bond at index 12.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 12.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:06] Conflicting single bond directions around double bond at index 17.
[10:38:06]   BondStereo set to STEREONONE and single bond directions set to NONE.
 50%|████▉     | 1595/3211 [00:00<00:00, 1955.95it/s][10:38:07] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP([O-])(=O)O[C@@H]1([C@H](O)[C@H](O)[C@@H](OP(=O)([O-])[O-])[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](OP([O-])([O-])=O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](OP([O-])([O-])=O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]' for input: 'C(OC(=O)[R1])[C@H](COP(=O)([O-])O[C@@H]1([C@H](O)[C@H](OP([O-])([O-])=O)[C@@H](O)[C@H](OP(=O)([O-])[O-])[C@@H](O)1))OC(=O)[R2]'
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
 56%|█████▌    | 1791/3211 [00:00<00:00, 1899.39it/s][10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] WARNING: not removing hydrogen atom without neighbors
 62%|██████▏   | 1982/3211 [00:01<00:00, 1861.79it/s][10:38:07] SMILES Parse Error: syntax error while parsing: C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]' for input: 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(/OC3(\C(/[C@H](O)C(/O)=2)=C([R6])/C(\[R7])=C([R8])\C(/[R9])=3)))[R4])[R3]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]' for input: 'C1(=C(C(\[R5])=C(C(/[R1])=C([R2])/1)/C2(C(/O)=C\C3(\C(\[O+]=2)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=3)))[R4])[R3]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)' for input: 'C3([R3])(C(/[R2])=C([R1])/C(/[C@@H]1([C@@H](O)[C@@H](O)C2(/C(\[R6])=C([R7])\C(/[R8])=C([R9])/C(/O1)=2)))=C([R5])\C(/[R4])=3)'
[10:38:07] SMILES Parse Error: syntax error while parsing: C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]' for input: 'C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]2O)=3))))O4)
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]2O)=3))))O4)' for input: 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@@H]2O)=3))))O4)'
[10:38:07] SMILES Parse Error: syntax error while parsing: C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]' for input: 'C3(C(/[R2])=C([R1])/C(/[C@H]1(OC2(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]1O)=2)))=C([R5])\C(/[R4])=3)[R3]'
[10:38:07] SMILES Parse Error: syntax error while parsing: C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]2O)=3))))O4)
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]2O)=3))))O4)' for input: 'C(O)[C@@H]4([C@@H](O)[C@H](O)[C@@H](O)[C@H](OC1(\C(/[R3])=C([R4])/C(\[R5])=C(C(\[R1])=1)/[C@H]2(OC3(\C(/[R9])=C([R8])/C(\[R7])=C([R6])\C(/C[C@H]2O)=3))))O4)'
[10:38:07] SMILES Parse Error: syntax error while parsing: C6(C(/[R2])=C([R1])/C(/C4(OC5(\C(/C1(C3(/C(\[R6])=C([R7])\C(/[R8])=C/C(/OC(C1O)C2(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=2))=3)))=C([R8])/C(\[R7])=C([R6])\C(/CC4O)=5)))=C([R5])\C(/[R4])=6)[R3]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C6(C(/[R2])=C([R1])/C(/C4(OC5(\C(/C1(C3(/C(\[R6])=C([R7])\C(/[R8])=C/C(/OC(C1O)C2(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=2))=3)))=C([R8])/C(\[R7])=C([R6])\C(/CC4O)=5)))=C([R5])\C(/[R4])=6)[R3]' for input: 'C6(C(/[R2])=C([R1])/C(/C4(OC5(\C(/C1(C3(/C(\[R6])=C([R7])\C(/[R8])=C/C(/OC(C1O)C2(\C(/[R1])=C([R2])/C(\[R3])=C([R4])\C(/[R5])=2))=3)))=C([R8])/C(\[R7])=C([R6])\C(/CC4O)=5)))=C([R5])\C(/[R4])=6)[R3]'
[10:38:07] SMILES Parse Error: syntax error while parsing: O=[a
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'O=[a' for input: 'O=[a'
 68%|██████▊   | 2187/3211 [00:01<00:00, 1916.26it/s][10:38:07] SMILES Parse Error: syntax error while parsing: C3([R3])(C(/[R4])=C([R5])/C(/C1(/OC2(/C(\[R9])=C([R8])\C(/[R7])=C([R6])/C(/C(=O)C(/O)=1)=2)))=C([R1])\C(/[R2])=3)
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C3([R3])(C(/[R4])=C([R5])/C(/C1(/OC2(/C(\[R9])=C([R8])\C(/[R7])=C([R6])/C(/C(=O)C(/O)=1)=2)))=C([R1])\C(/[R2])=3)' for input: 'C3([R3])(C(/[R4])=C([R5])/C(/C1(/OC2(/C(\[R9])=C([R8])\C(/[R7])=C([R6])/C(/C(=O)C(/O)=1)=2)))=C([R1])\C(/[R2])=3)'
[10:38:07] SMILES Parse Error: syntax error while parsing: C(O)[C@@H]1([C@@H](O)[C@H](O)[C@@H](O)[C@@H](O1)OC3(\C(=O)C4(\C(\OC(\C2(/C(\[R1])=C([R2])\C(/[R3])=C([R4])/C(\[R5])=2))=3)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=4)))
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'C(O)[C@@H]1([C@@H](O)[C@H](O)[C@@H](O)[C@@H](O1)OC3(\C(=O)C4(\C(\OC(\C2(/C(\[R1])=C([R2])\C(/[R3])=C([R4])/C(\[R5])=2))=3)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=4)))' for input: 'C(O)[C@@H]1([C@@H](O)[C@H](O)[C@@H](O)[C@@H](O1)OC3(\C(=O)C4(\C(\OC(\C2(/C(\[R1])=C([R2])\C(/[R3])=C([R4])/C(\[R5])=2))=3)=C([R9])/C(\[R8])=C([R7])\C(/[R6])=4)))'
 75%|███████▍  | 2397/3211 [00:01<00:00, 1968.23it/s][10:38:07] SMILES Parse Error: syntax error while parsing: CC(C)=CCCC(\C)=C/CCC(\C)=C/CC[R]CC(/C)=C/CCC(/C)=C/CCC(/C)=C/COP([O-])(=O)OP(=O)([O-])[O-]
[10:38:07] SMILES Parse Error: Failed parsing SMILES 'CC(C)=CCCC(\C)=C/CCC(\C)=C/CC[R]CC(/C)=C/CCC(/C)=C/CCC(/C)=C/COP([O-])(=O)OP(=O)([O-])[O-]' for input: 'CC(C)=CCCC(\C)=C/CCC(\C)=C/CC[R]CC(/C)=C/CCC(/C)=C/CCC(/C)=C/COP([O-])(=O)OP(=O)([O-])[O-]'
 87%|████████▋ | 2789/3211 [00:01<00:00, 1852.28it/s][10:38:07] Conflicting single bond directions around double bond at index 12.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:38:07] Conflicting single bond directions around double bond at index 17.
[10:38:07]   BondStereo set to STEREONONE and single bond directions set to NONE.
 93%|█████████▎| 2977/3211 [00:01<00:00, 1859.90it/s][10:38:07] SMILES Parse Error: syntax error while parsing: [R]
[10:38:07] SMILES Parse Error: Failed parsing SMILES '[R]' for input: '[R]'
100%|██████████| 3211/3211 [00:01<00:00, 1911.30it/s]

In [ ]:
plantcyc_ = plantcyc.drop(to_drop)
plantcyc_["inchikey"] = inchikeys
plantcyc_["inchikey_wo_last"] = inchikeys_wo_last
plantcyc_.to_csv("../plantcyc/plantcyc_w_inchikey.csv", index=False)
plantcyc_

,Pathway ID,Type,Pathway Name,Metabolite,Name,SMILES,inchikey,inchikey_wo_last
0,PWY-6232,FLAVONOID-SYN,chrysoeriol biosynthesis,5734-TETRAHYDROXYFLAVONE,luteolin,C3(/C=C(C(/O)=C\C(\C1(\OC2(/C=C(/C=C(C(\C(=O)\...,IQPNAANSBPBGFQ-UHFFFAOYSA-M,IQPNAANSBPBGFQ-UHFFFAOYSA-
1,PWY-6232,FLAVONOID-SYN,chrysoeriol biosynthesis,574-TRIHYDROXY-3-METHOXYFLAVONE,chrysoeriol,COC1(\C(\O)=C/C=C(/C=1)/C2(/OC3(/C=C(/C=C(C(\C...,SCZVLDHREVKTSH-UHFFFAOYSA-M,SCZVLDHREVKTSH-UHFFFAOYSA-
2,PWY0A-6303,Auxin-Biosynthesis,methyl indole-3-acetate interconversion,CPD-10546,methyl (indol-3-yl)acetate,COC(=O)CC1(\C2(\C(\N\C=1)=C/C=C\C=2)),KTHADMDGDNYQRX-UHFFFAOYSA-N,KTHADMDGDNYQRX-UHFFFAOYSA-
3,PWY0A-6303,Auxin-Biosynthesis,methyl indole-3-acetate interconversion,INDOLE_ACETATE_AUXIN,(indol-3-yl)acetate,C([O-])(=O)CC1(\C2(/C=C\C=C/C(/N\C=1)=2)),SEOVTRFCIGRIMH-UHFFFAOYSA-M,SEOVTRFCIGRIMH-UHFFFAOYSA-
4,PWY-5409,Divinyl-Ether-Biosynthesis,divinyl ether biosynthesis II,LINOLEIC_ACID,linoleate,CCCCC\C=C/C\C=C/CCCCCCCC([O-])=O,OYHQOLUKZRVURQ-HZJYTTRNSA-M,OYHQOLUKZRVURQ-HZJYTTRNSA-
...,...,...,...,...,...,...,...,...
3206,PWY-5925,Siderophores-Biosynthesis,hydroxylated mugineic acid phytosiderophore bi...,CPD-7231,mugineate,C1(C[C@@H](C([O-])=O)N1C[C@H](O)[C@H]([NH2+]CC...,GJRGEVKCJPPZIT-JBDRJPRFSA-L,GJRGEVKCJPPZIT-JBDRJPRFSA-
3207,PWY-5925,Siderophores-Biosynthesis,hydroxylated mugineic acid phytosiderophore bi...,CPD-7289,3-epihydroxymugineate,C1([C@H](O)[C@@H](C([O-])=O)N1C[C@H](O)[C@H]([...,QPIOQLJXMZWNFJ-LJASKYJCSA-L,QPIOQLJXMZWNFJ-LJASKYJCSA-
3208,PWY18C3-18,DITERPENOID-SYN,labdenediol and sclareol biosynthesis,CPD-12745,(13<i>E</i>)-8&alpha;-hydroxylabd-13-en-15-yl ...,CC(/CC[C@@H]1([C@]2(CCCC(C)(C)[C@@H](CC[C@](O)...,ZDGVATANBJCRHY-HHQLMWAKSA-K,ZDGVATANBJCRHY-HHQLMWAKSA-
3209,PWY18C3-18,DITERPENOID-SYN,labdenediol and sclareol biosynthesis,CPD-10110,sclareol,C=C[C@](C)(O)CC[C@H]1([C@](C)(O)CC[C@H]2(C(C)(...,XVULBTBTFGYVRC-HHUCQEJWSA-N,XVULBTBTFGYVRC-HHUCQEJWSA-
3210,PWY18C3-18,DITERPENOID-SYN,labdenediol and sclareol biosynthesis,CPD-18878,"(13<i>E</i>)-labdene-8alpha,15-diol",CC(/CC[C@H]2([C@](C)(O)CCC1([C@](C)(CCCC(C)(C)...,LEOHDQKUMQKLMP-YHOUDPESSA-N,LEOHDQKUMQKLMP-YHOUDPESSA-

In [39]:
final_dataset_filtered = final_dataset[~final_dataset['inchikey_wo_last'].isin(plantcyc_['inchikey_wo_last'])]
final_dataset_filtered

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
810463,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
810464,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
810465,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
810466,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
810467,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

## KEGG pathways

In [ ]:
import pandas as pd

kegg = pd.read_csv("../kegg/kegg_pathways_v1.csv")

from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(kegg.SMILES), total=kegg.shape[0]):
    try:
        mol = MolFromSmiles(smiles)
        if mol is not None:
            inchikey = MolToInchiKey(mol)
            inchikeys.append(inchikey)
            inchikeys_wo_last.append(inchikey[:-1])
        else:
            to_drop.append(i)

    except:
        to_drop.append(i)

kegg_ = kegg.drop(to_drop)
kegg_["inchikey"] = inchikeys
kegg_["inchikey_wo_last"] = inchikeys_wo_last
kegg_.to_csv("kegg/kegg_pathways_w_inchikey.csv", index=False)
kegg_

  0%|          | 0/2014 [00:00<?, ?it/s]

[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
 12%|█▏        | 237/2014 [00:00<00:00, 2359.48it/s][10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:28] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
 23%|██▎       | 473/2014 [00:00<00:00, 1750.86it/s][10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
 43%|████▎     | 862/2014 [00:00<00:00, 1421.24it/s][10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
 51%|█████▏    | 1036/2014 [00:00<00:00, 1507.68it/s][10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
 70%|██████▉   | 1403/2014 [00:00<00:00, 1668.38it/s][10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
[10:42:29] Invalid InChI prefix in generating InChI Key
100%|██████████| 2014/2014 [00:01<00:00, 1742.24it/s]

,Pathway,Pathway Name,Metabolite,SMILES,inchikey,inchikey_wo_last
0,map00010,Glycolysis / Gluconeogenesis,C00022,CC(=O)C(=O)O,LCTONWCANYUPML-UHFFFAOYSA-N,LCTONWCANYUPML-UHFFFAOYSA-
1,map00010,Glycolysis / Gluconeogenesis,C00024,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,ZSLZBFCDCINBPY-ZSJPKINUSA-N,ZSLZBFCDCINBPY-ZSJPKINUSA-
2,map00010,Glycolysis / Gluconeogenesis,C00031,OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O,WQZGKKKJIJFFOK-GASJEMHNSA-N,WQZGKKKJIJFFOK-GASJEMHNSA-
3,map00010,Glycolysis / Gluconeogenesis,C00033,CC(=O)O,QTBSBXVTEAMEQO-UHFFFAOYSA-N,QTBSBXVTEAMEQO-UHFFFAOYSA-
4,map00010,Glycolysis / Gluconeogenesis,C00036,O=C(O)CC(=O)C(=O)O,KHPXUQMNIQBQEV-UHFFFAOYSA-N,KHPXUQMNIQBQEV-UHFFFAOYSA-
...,...,...,...,...,...,...
2009,map01070,Biosynthesis of plant hormones,C08814,CC(C)[C@H](C)[C@@H](O)[C@H](O)[C@@H](C)[C@H]1C...,IXVMHGVQKLDRKH-KNBKMWSGSA-N,IXVMHGVQKLDRKH-KNBKMWSGSA-
2010,map01070,Biosynthesis of plant hormones,C09190,CC1=C[C@H](O/C=C2/C(=O)O[C@@H]3C4=C(C[C@H]23)[...,VOFXXOPWCBSPAA-KCNJUGRMSA-N,VOFXXOPWCBSPAA-KCNJUGRMSA-
2011,map01070,Biosynthesis of plant hormones,C11434,C[C@](O)(CO)[C@H](O)COP(=O)(O)O,XMWHRVNVKDKBRG-UHNVWZDZSA-N,XMWHRVNVKDKBRG-UHNVWZDZSA-
2012,map01070,Biosynthesis of plant hormones,C11437,CC(=O)[C@@H](O)[C@H](O)COP(=O)(O)O,AJPADPZSRRUGHI-RFZPGFLSSA-N,AJPADPZSRRUGHI-RFZPGFLSSA-
2013,map01070,Biosynthesis of plant hormones,C15545,C/C(=C/CNc1ncnc2[nH]cnc12)CO,UZKQTCBAMSWPJD-UQCOIBPSSA-N,UZKQTCBAMSWPJD-UQCOIBPSSA-

In [40]:
final_dataset_filtered = final_dataset_filtered[~final_dataset_filtered['inchikey_wo_last'].isin(kegg_['inchikey_wo_last'])]
final_dataset_filtered

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
810463,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
810464,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
810465,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
810466,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
810467,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

## SM precursors predictor

In [ ]:
import pandas as pd

precursors_predictor = pd.read_csv("../precursors/final_dataset_top_v2.csv")

from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(precursors_predictor.smiles), total=precursors_predictor.shape[0]):
    try:
        mol = MolFromSmiles(smiles)
        if mol is not None:
            inchikey = MolToInchiKey(mol)
            inchikeys.append(inchikey)
            inchikeys_wo_last.append(inchikey[:-1])
        else:
            to_drop.append(i)

    except:
        to_drop.append(i)

precursors_predictor_ = precursors_predictor.drop(to_drop)
precursors_predictor_["inchikey"] = inchikeys
precursors_predictor_["inchikey_wo_last"] = inchikeys_wo_last
precursors_predictor_.to_csv("precursors_predictor/precursors_predictor_w_inchikey.csv", index=False)
precursors_predictor_

  0%|          | 0/1428 [00:00<?, ?it/s]

 16%|█▋        | 233/1428 [00:00<00:00, 2326.52it/s][10:45:01] Invalid InChI prefix in generating InChI Key
[10:45:01] Invalid InChI prefix in generating InChI Key
[10:45:01] Invalid InChI prefix in generating InChI Key
[10:45:01] Invalid InChI prefix in generating InChI Key
[10:45:01] Invalid InChI prefix in generating InChI Key
[10:45:01] Invalid InChI prefix in generating InChI Key
100%|██████████| 1428/1428 [00:00<00:00, 1851.95it/s]

,ids,smiles,C00073,C00078,C00079,C00082,C00235,C00341,C00353,C00448,...,C00509,C00540,C01477,C05903,C05904,C05905,C05908,C09762,inchikey,inchikey_wo_last
0,C02344,CC1(C)[C@@H]2CC[C@@](C)(C2)[C@@H]1O,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,IAIHUHQCLTYTSF-MRTMQBJTSA-N,IAIHUHQCLTYTSF-MRTMQBJTSA-
1,C02462,CC(C)[C@]12CC[C@@](C)(O)[C@H]1C2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,KXSDPILWMGFJMM-OPRDCNLKSA-N,KXSDPILWMGFJMM-OPRDCNLKSA-
2,C03190,CC1(C)C2CCC1(C)[C@@H](OP(=O)(O)OP(=O)(O)O)C2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,VZPAJODTZAAANV-ZCUBBSJVSA-N,VZPAJODTZAAANV-ZCUBBSJVSA-
3,C06074,C=CC(=C)CCC=C(C)C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,UAHWPYUMFXYFJY-UHFFFAOYSA-N,UAHWPYUMFXYFJY-UHFFFAOYSA-
4,C00521,C=C(C)[C@@H]1CC=C(C)CC1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,XMGQYMWWDOXHJM-SNVBAGLBSA-N,XMGQYMWWDOXHJM-SNVBAGLBSA-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,C00002242,C1(C(C(C(C(O1)(OC2(C(C(C(OC2(C(O[H])([H])[H])[...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,TYNQWWGVEGFKRU-UHFFFAOYSA-N,TYNQWWGVEGFKRU-UHFFFAOYSA-
1424,C00030216,C1(C(C(C2(C(C1([H])[H])(C3(C(C(C2([H])[H])([H]...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,VSQBWNYALURFOT-UHFFFAOYSA-N,VSQBWNYALURFOT-UHFFFAOYSA-
1425,C00002264,O(C1(C(C=2C(C(C1([H])[H])([H])[H])(C3(C(C(C2[H...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,KWVISVAMQJWJSZ-UHFFFAOYSA-N,KWVISVAMQJWJSZ-UHFFFAOYSA-
1426,C00002265,C1(C(C(C(C(O1)(OC2(C(C(C(OC2(OC3(C(C=4C(C(C3([...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,QCTMYNGDIBTNSK-UHFFFAOYSA-N,QCTMYNGDIBTNSK-UHFFFAOYSA-
1427,C00002260,C1(C(C(C(C(O1)(OC2(C(C(C(OC2(OC3(C(C=4C(C(C3([...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MBWUSSKCCUMJHO-UHFFFAOYSA-N,MBWUSSKCCUMJHO-UHFFFAOYSA-

In [41]:
final_dataset_filtered = final_dataset_filtered[~final_dataset_filtered['inchikey_wo_last'].isin(precursors_predictor_['inchikey_wo_last'])]
final_dataset_filtered

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
810463,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
810464,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
810465,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
810466,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
810467,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

## NP classifier

In [ ]:
import pandas as pd

np_classifier = pd.read_csv("../np_classifier/test_dataset.csv")

from rdkit.Chem import MolFromSmiles, MolToInchiKey
from tqdm import tqdm

inchikeys = []
inchikeys_wo_last = []
to_drop = []
for i, smiles in tqdm(enumerate(np_classifier.SMILES), total=np_classifier.shape[0]):
    try:
        mol = MolFromSmiles(smiles)
        if mol is not None:
            inchikey = MolToInchiKey(mol)
            inchikeys.append(inchikey)
            inchikeys_wo_last.append(inchikey[:-1])
        else:
            to_drop.append(i)

    except:
        to_drop.append(i)

np_classifier_ = np_classifier.drop(to_drop)
np_classifier_["inchikey"] = inchikeys
np_classifier_["inchikey_wo_last"] = inchikeys_wo_last
np_classifier_.to_csv("np_classifier/np_classifier_w_inchikey.csv", index=False)
np_classifier_

100%|██████████| 15541/15541 [00:09<00:00, 1573.62it/s]

,key,SMILES,Alkaloids,Amino acids and Peptides,Carbohydrates,Fatty acids,Polyketides,Shikimates and Phenylpropanoids,Terpenoids,Alkylresorsinols,...,Wax monoesters,Xeniaphyllane diterpenoids,Xenicane diterpenoids,Yohimbine-like alkaloids,Zearalenones,Zizaane sesquiterpenoids,m-Terphenyls,p-Terphenyls,inchikey,inchikey_wo_last
0,XFBQQSLGCORCGH,CCCCC/C=C\C/C=C\CCCCCCCC(=O)OC[C@@H](COC(=O)CC...,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,XFBQQSLGCORCGH-FNWDFWSHSA-N,XFBQQSLGCORCGH-FNWDFWSHSA-
1,UBJDLKGJDZONCO,COc1cc(C2Oc3cc4c(cc3C2COC(C)=O)-c2c(cc(O)cc2OC...,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,UBJDLKGJDZONCO-UHFFFAOYSA-N,UBJDLKGJDZONCO-UHFFFAOYSA-
2,WCXMGPNELNHROM,COc1cc2c(cc1O)OC(c1ccccc1)CC2=O,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,WCXMGPNELNHROM-UHFFFAOYSA-N,WCXMGPNELNHROM-UHFFFAOYSA-
3,XRBNWTBBMTUZLA,COc1cccc(CCOC2OC(CO)C(OC(=O)C=Cc3ccc(O)c(O)c3)...,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,XRBNWTBBMTUZLA-UHFFFAOYSA-N,XRBNWTBBMTUZLA-UHFFFAOYSA-
4,WDDXJPVDQFRGNC,CC(C)c1c(O)ccc2c1C(=O)CC1C(C)(C(=O)O)CCCC21C,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,WDDXJPVDQFRGNC-UHFFFAOYSA-N,WDDXJPVDQFRGNC-UHFFFAOYSA-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15536,COVDAEBDAVGGFK,CC(C)=CCC/C(C)=C/C/C=C(\C)[C@H](O)Cc1c[nH]c([N...,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,COVDAEBDAVGGFK-CIBVNXTLSA-N,COVDAEBDAVGGFK-CIBVNXTLSA-
15537,TXTGITRXQUOAJM,COC1Oc2ccccc2-c2c1oc1cc(O)c(C)c(O)c1c2=O,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,TXTGITRXQUOAJM-UHFFFAOYSA-N,TXTGITRXQUOAJM-UHFFFAOYSA-
15538,VUAIYBIBQXIJKV,Cc1c2c(cc3c1CC(C)(C)C3=O)C(=O)OCC2,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,VUAIYBIBQXIJKV-UHFFFAOYSA-N,VUAIYBIBQXIJKV-UHFFFAOYSA-
15539,HFPLCFMATPQWMD,O=C(O)CC(Cl)Cl,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,HFPLCFMATPQWMD-UHFFFAOYSA-N,HFPLCFMATPQWMD-UHFFFAOYSA-
15540,GCEVIODPDGBRSE,CC(=O)OC1C2C(O)C(OC(=O)c3ccccc3)C3(C)C(OC(=O)c...,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,GCEVIODPDGBRSE-UHFFFAOYSA-N,GCEVIODPDGBRSE-UHFFFAOYSA-

In [42]:
final_dataset_filtered = final_dataset_filtered[~final_dataset_filtered['inchikey_wo_last'].isin(np_classifier_['inchikey_wo_last'])]
final_dataset_filtered

,ids,smiles,inchikey_wo_last
0,CNP0282693.1,COc1cccc2c1C(=O)c1c(O)c3c(C[C@@](O)(C(=O)CO)C[...,ITSGNOIFAJAQHJ-BMFNZSJVSA-
1,CNP0214016.1,COc1cc2cc(c1Cl)N(C)C(=O)C[C@H](OC(=O)[C@H](C)N...,WKPWGQKGSOKKOO-RSFHAFMBSA-
2,CNP0185052.1,Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...,NYQPLPNEESYGNO-IBGZPJMESA-
3,CNP0074548.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(COC(N)...,JFPVXVDWJQMJEE-IZRZKJBUSA-
4,CNP0602851.1,CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...,YWKJNRNSJKEFMK-PQFQYKRASA-
...,...,...,...
810463,LTS0113043,CC(=CC(C)CCCCC(=O)O)C1OC2C=CC1OC(=O)C=CC=CC=CC...,OTABDKFPJQZJRD-UHFFFAOYSA-
810464,LTS0183570,CCC(C)CCCCCC/C=C\CCC(=O)O,VMOMGLBYFJYDMH-CLFYSBASSA-
810465,LTS0059294,C=C1C[C@@H]2OC(=O)[C@H](C)[C@H]2[C@@H](O)/C=C(...,AMBNTPYCDHUUJH-GFNKKNRCSA-
810466,LTS0117662,CCc1c(OC)oc(CCCCCCCCCC(C)O)c(C)c1=O,SGIFMADMFIWPSQ-UHFFFAOYSA-
810467,LTS0137387,CC1=C(C)C2C(Cc3ccccc3)N=C(O)C23OC(=O)CCC(=O)CC...,MUWRTUOAFXGGOC-UHFFFAOYSA-

In [43]:
final_dataset_filtered.to_csv("integrated_dataset_km_training_wo_fintuning_datasets.csv", index=False)

# Split the data

In [48]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(final_dataset_filtered, test_size=0.1, random_state=420)

In [49]:
train, validation = train_test_split(final_dataset_filtered, test_size=0.05, random_state=420)

In [50]:
train.to_csv("train_test_split_random/train_lm.csv", index=False)
test.to_csv("train_test_split_random/test_lm.csv", index=False)
validation.to_csv("train_test_split_random/validation_lm.csv", index=False)

In [1]:
from deepmol.loaders import CSVLoader

dataset = CSVLoader(dataset_path="integrated_dataset_km_training_wo_fintuning_datasets.csv", smiles_field="smiles", id_field="ids").create_dataset(sep=",")

/home/jcapela/miniconda3/envs/pathway_prediction/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[10:53:45] WARNING: not removing hydrogen atom without neighbors
[10:53:45] WARNING: not removing hydrogen atom without neighbors
[10:53:56] WARNING: not removing hydrogen atom without neighbors

In [2]:
from deepmol.splitters import ScaffoldSplitter

scaffold_splitter = ScaffoldSplitter()

train_dataset, valid_dataset, test_dataset = scaffold_splitter.train_valid_test_split(dataset, frac_train=0.8, frac_valid=0.1, frac_test=0.1, homogenous_datasets = False)

In [6]:

train_dataset.to_csv(path="train_test_split_scaffolds/train_dataset.csv", index=False)
valid_dataset.to_csv(path="train_test_split_scaffolds/validation_dataset.csv", index=False)
test_dataset.to_csv(path="train_test_split_scaffolds/test_dataset.csv", index=False)

In [2]:
from deepmol.loaders import CSVLoader

loader = CSVLoader(dataset_path="train_test_split_scaffolds/train_dataset.csv",
                           smiles_field='smiles',
                           id_field='ids',
                           mode='auto')
train_dataset = loader.create_dataset(sep=',')

loader = CSVLoader(dataset_path="train_test_split_scaffolds/validation_dataset.csv",
                           smiles_field='smiles',
                           id_field='ids',
                           mode='auto')
validation_dataset = loader.create_dataset(sep=',')

loader = CSVLoader(dataset_path="train_test_split_scaffolds/test_dataset.csv",
                           smiles_field='smiles',
                           id_field='ids',
                           mode='auto')
test_dataset = loader.create_dataset(sep=',')

/home/jcapela/miniconda3/envs/pathway_prediction/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[14:50:13] WARNING: not removing hydrogen atom without neighbors
[14:51:41] WARNING: not removing hydrogen atom without neighbors
[14:51:41] WARNING: not removing hydrogen atom without neighbors

In [3]:
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from tqdm import tqdm

def compute_fingerprint(molecule):
    fingerprint = AllChem.GetMorganFingerprintAsBitVect(molecule, 2, nBits=1024)
    return fingerprint

# Compute molecular fingerprints for each molecule in the combined dataset
train_dataset_fingerprints = [compute_fingerprint(smiles) for smiles in train_dataset.mols]
test_dataset_fingerprints = [compute_fingerprint(smiles) for smiles in test_dataset.mols]

In [4]:
validation_dataset_fingerprints = [compute_fingerprint(smiles) for smiles in validation_dataset.mols]

In [ ]:
max_score = 0
more_than_0_6 = 0

to_drop = []

import numpy as np
from tqdm import tqdm

for i in tqdm(range(len(validation_dataset_fingerprints))):
    scores = DataStructs.BulkTanimotoSimilarity(validation_dataset_fingerprints[i], train_dataset_fingerprints)
    max_score_ = np.max(scores)
    if max_score < max_score_:
        max_score = max_score_
    
    if max_score_ > 0.6:
        to_drop.append(i)

In [20]:
validation_dataset.remove_elements_by_index(to_drop, inplace=True)

In [21]:
validation_dataset.to_dataframe()

                ids                                             smiles
0      CNP0298093.1             CO[C@@]1(/C=C/c2ccccc2)OC(=O)C(CO)=C1C
1        LTS0198741                   COC1(C=Cc2ccccc2)OC(=O)C(CO)=C1C
2      CNP0443954.1  COC(C[C@@H](c1c(C[C@@H]2NC(=O)[C@@H](Cc3ccccc3...
3      CNP0443067.1  COC(=O)C(C[C@H](c1c(C[C@@H]2NC(=O)[C@@H](Cc3cc...
4      CNP0467518.1  C[C@H]1CN2C(=O)[C@H]3/C=C\C=C/[C@H]4[C@@H](C=C...
...             ...                                                ...
67904  CNP0305311.1  CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)O)=C(/C=C/S...
67905  CNP0592181.1  CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...
67906  CNP0074843.1  O=C(O)c1cccc(/C=C2\C[C@H]3C[C@@H](O)[C@H](/C=C...
67907  CNP0602851.1  CO/N=C(\C(=O)N[C@@H]1C(=O)N2C(C(=O)[O-])=C(C[n...
67908  CNP0185052.1  Nc1nc(N)c2nc(CNc3ccc(C(=O)N[C@@H](CCCNC(=O)c4c...

[67909 rows x 2 columns]

In [6]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from tqdm import tqdm

def check_similarity_all_compounds(dataset, smiles_field):
    def compute_fingerprint(smiles):
        molecule = Chem.MolFromSmiles(smiles)
        fingerprint = AllChem.GetMorganFingerprintAsBitVect(molecule, 2, nBits=1024)
        return fingerprint

    # Compute molecular fingerprints for each molecule in the combined dataset
    fingerprints = [compute_fingerprint(smiles) for smiles in dataset.loc[:, smiles_field]]

    similarity_1_pairs = {} 

    # Compute molecular similarities using Tanimoto coefficient
    for i in tqdm(range(len(fingerprints))):
        for j in range(i + 1, len(fingerprints)):
            similarity = DataStructs.TanimotoSimilarity(fingerprints[i], fingerprints[j])
            if similarity == 1:
                similar_compounds = similarity_1_pairs.get(i, [])

                similar_compounds.append(j)
                similarity_1_pairs[i] = similar_compounds

    return similarity_1_pairs